joinfaces:
  jsf:
    PROJECT_STAGE: Production
    FACELETS_LIBRARIES: /tags/tags.taglib.xml
  primefaces:
    theme: vela
tomcat:
  version: @tomcat.version@
jetty:
  version: @jetty.version@
undertow:
  version: @undertow.version@